"""empty message

Revision ID: 149222e569d1
Revises: 0c2ed5e1a2f1
Create Date: 2024-02-24 16:15:31.083469

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils.types.choice

# revision identifiers, used by Alembic.
revision = '149222e569d1'
down_revision = '0c2ed5e1a2f1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('p2p_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('github_link', sa.String(), nullable=True),
    sa.Column('comment', sa.String(), nullable=True),
    sa.Column('creator', sa.Integer(), nullable=True),
    sa.Column('publication_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('review_state', sqlalchemy_utils.types.choice.ChoiceType(choices=(('ready', 'Ready'), ('progress', 'Progress'), ('completed', 'Completed'))), nullable=True),
    sa.Column('reviewer', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['creator'], ['users.id'], ),
    sa.ForeignKeyConstraint(['reviewer'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_p2p_requests_github_link'), 'p2p_requests', ['github_link'], unique=False)
    op.create_index(op.f('ix_p2p_requests_id'), 'p2p_requests', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_p2p_requests_id'), table_name='p2p_requests')
    op.drop_index(op.f('ix_p2p_requests_github_link'), table_name='p2p_requests')
    op.drop_table('p2p_requests')
    # ### end Alembic commands ###
