"""empty message

Revision ID: 2a21ae496bbc
Revises: 5acd0e76053c
Create Date: 2024-03-11 23:03:59.876530

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2a21ae496bbc'
down_revision = '5acd0e76053c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('p2p_reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('link', sa.String()),
    sa.Column('creation_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('review_state', postgresql.ENUM('pending', 'progress', 'completed', name='review_state_enums', create_type=False), nullable=False),
    sa.Column('reviewer_id', sa.Integer(), nullable=False),
    sa.Column('p2p_request_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['p2p_request_id'], ['p2p_requests.id'], ),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_p2p_reviews_id'), 'p2p_reviews', ['id'], unique=False)
    op.drop_constraint('p2p_requests_reviewer_id_fkey', 'p2p_requests', type_='foreignkey')
    op.drop_column('p2p_requests', 'reviewer_id')
    op.drop_column('p2p_requests', 'review_state')
    op.drop_column('p2p_requests', 'review_start_date')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('p2p_requests', sa.Column('review_start_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('p2p_requests', sa.Column('review_state', postgresql.ENUM('pending', 'progress', 'completed', name='review_state_enums', create_type=False), autoincrement=False, nullable=False))
    op.add_column('p2p_requests', sa.Column('reviewer_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('p2p_requests_reviewer_id_fkey', 'p2p_requests', 'users', ['reviewer_id'], ['id'])
    op.drop_index(op.f('ix_p2p_reviews_id'), table_name='p2p_reviews')
    op.drop_table('p2p_reviews')
    # ### end Alembic commands ###
