"""empty message

Revision ID: 5acd0e76053c
Revises: 
Create Date: 2024-03-08 15:19:05.147940

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5acd0e76053c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('pending', 'progress', 'completed', name='review_state_enums').create(op.get_bind())
    op.create_table('scopes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scopes_id'), 'scopes', ['id'], unique=False)
    op.create_index(op.f('ix_scopes_name'), 'scopes', ['name'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('discord_id', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_discord_id'), 'users', ['discord_id'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('p2p_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('repository_link', sa.String(), nullable=False),
    sa.Column('comment', sa.String(), nullable=False),
    sa.Column('creator_id', sa.Integer(), nullable=False),
    sa.Column('publication_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('review_state', postgresql.ENUM('pending', 'progress', 'completed', name='review_state_enums', create_type=False), nullable=False),
    sa.Column('reviewer_id', sa.Integer(), nullable=True),
    sa.Column('review_start_date', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_p2p_requests_id'), 'p2p_requests', ['id'], unique=False)
    op.create_index(op.f('ix_p2p_requests_repository_link'), 'p2p_requests', ['repository_link'], unique=False)
    op.create_table('users_to_scopes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('scope_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['scope_id'], ['scopes.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'scope_id')
    )
    op.create_index(op.f('ix_users_to_scopes_id'), 'users_to_scopes', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_to_scopes_id'), table_name='users_to_scopes')
    op.drop_table('users_to_scopes')
    op.drop_index(op.f('ix_p2p_requests_repository_link'), table_name='p2p_requests')
    op.drop_index(op.f('ix_p2p_requests_id'), table_name='p2p_requests')
    op.drop_table('p2p_requests')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_discord_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_scopes_name'), table_name='scopes')
    op.drop_index(op.f('ix_scopes_id'), table_name='scopes')
    op.drop_table('scopes')
    sa.Enum('pending', 'progress', 'completed', name='review_state_enums').drop(op.get_bind())
    # ### end Alembic commands ###
