"""empty message

Revision ID: 5ea3d3527a03
Revises: a930d03d907d
Create Date: 2024-02-26 23:32:22.672904

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils.types.choice

# revision identifiers, used by Alembic.
revision = '5ea3d3527a03'
down_revision = 'a930d03d907d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('p2p_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('repository_link', sa.String(), nullable=False),
    sa.Column('comment', sa.String(), nullable=False),
    sa.Column('creator_id', sa.Integer(), nullable=False),
    sa.Column('publication_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('review_state', sqlalchemy_utils.types.choice.ChoiceType(choices=(('pending', 'Pending'), ('progress', 'Progress'), ('completed', 'Completed'))), nullable=False),
    sa.Column('reviewer_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_p2p_requests_id'), 'p2p_requests', ['id'], unique=False)
    op.create_index(op.f('ix_p2p_requests_repository_link'), 'p2p_requests', ['repository_link'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_p2p_requests_repository_link'), table_name='p2p_requests')
    op.drop_index(op.f('ix_p2p_requests_id'), table_name='p2p_requests')
    op.drop_table('p2p_requests')
    # ### end Alembic commands ###
