"""empty message

Revision ID: 714a1f19cb41
Revises: bb0027858aee
Create Date: 2024-02-24 18:46:33.542114

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '714a1f19cb41'
down_revision = 'bb0027858aee'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
