"""empty message

Revision ID: bb0027858aee
Revises: 149222e569d1
Create Date: 2024-02-24 18:42:35.933670

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb0027858aee'
down_revision = '149222e569d1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('p2p_requests', sa.Column('repository_link', sa.String(), nullable=True))
    op.add_column('p2p_requests', sa.Column('creator_id', sa.Integer(), nullable=True))
    op.add_column('p2p_requests', sa.Column('reviewer_id', sa.Integer(), nullable=True))
    op.drop_index('ix_p2p_requests_github_link', table_name='p2p_requests')
    op.create_index(op.f('ix_p2p_requests_repository_link'), 'p2p_requests', ['repository_link'], unique=False)
    op.drop_constraint('p2p_requests_creator_fkey', 'p2p_requests', type_='foreignkey')
    op.drop_constraint('p2p_requests_reviewer_fkey', 'p2p_requests', type_='foreignkey')
    op.create_foreign_key(None, 'p2p_requests', 'users', ['reviewer_id'], ['id'])
    op.create_foreign_key(None, 'p2p_requests', 'users', ['creator_id'], ['id'])
    op.drop_column('p2p_requests', 'creator')
    op.drop_column('p2p_requests', 'github_link')
    op.drop_column('p2p_requests', 'reviewer')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('p2p_requests', sa.Column('reviewer', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('p2p_requests', sa.Column('github_link', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('p2p_requests', sa.Column('creator', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'p2p_requests', type_='foreignkey')
    op.drop_constraint(None, 'p2p_requests', type_='foreignkey')
    op.create_foreign_key('p2p_requests_reviewer_fkey', 'p2p_requests', 'users', ['reviewer'], ['id'])
    op.create_foreign_key('p2p_requests_creator_fkey', 'p2p_requests', 'users', ['creator'], ['id'])
    op.drop_index(op.f('ix_p2p_requests_repository_link'), table_name='p2p_requests')
    op.create_index('ix_p2p_requests_github_link', 'p2p_requests', ['github_link'], unique=False)
    op.drop_column('p2p_requests', 'reviewer_id')
    op.drop_column('p2p_requests', 'creator_id')
    op.drop_column('p2p_requests', 'repository_link')
    # ### end Alembic commands ###
