"""empty message

Revision ID: d4e70f4f8b93
Revises: cdd89efd0474
Create Date: 2024-03-08 14:58:38.269324

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd4e70f4f8b93'
down_revision = 'cdd89efd0474'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('pending', 'progress', 'completed', name='review_state_enums').create(op.get_bind())
    op.alter_column('p2p_requests', 'review_state',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Enum('pending', 'progress', 'completed', name='review_state_enums'),
               existing_nullable=False,
               postgresql_using='review_state::review_state_enums')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('p2p_requests', 'review_state',
               existing_type=sa.Enum('pending', 'progress', 'completed', name='review_state_enums'),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    sa.Enum('pending', 'progress', 'completed', name='review_state_enums').drop(op.get_bind())
    # ### end Alembic commands ###
