name: Pytest automatic testing

on: [push]

env:
  SECRET_KEY: secret-key-for-test
  ALGORITHM: HS256
  ACCESS_TOKEN_EXPIRE_MINUTES: 120
  DATABASE_URL: postgresql://postgres:postgres@localhost:5432/plug
  ORIGINS: "http://127.0.0.1:8000, http://localhost:8000"
  TOKEN_URL: token
  DEBUG: False
  DATABASE_URL_TEST: postgresql://postgres:postgres@localhost:5432/github_actions_db_test_db
  IS_TEST: True

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./API
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: github_actions_db_test_db
        ports:
          - 5432:5432
        # needed because the postgres container does not provide a healthcheck
        # TODO Никогда не настраивал воркфлоу для каких-то сложных проектов, но если это запускается как докер,
        # то там вообще есть healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"
    - name: Install dependencies
      working-directory: ./
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run migrations
      run: alembic upgrade head
    - name: Run tests
      run: python -m pytest
